apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server-deployment
spec:
  selector:
    matchLabels:
      app: config-server
    replicas: 2
    template:
      metadata:
        labels:
          app: config-server
        spec:
          containers:
            - name: config-server
              image: config-server:v0.0.1
              ports:
                - containerPort: 4040
