version: "3"

services:
  config-server:
    image: config-server
    container_name: config-server
    ports:
      - '4040:8080'
    command:
      - "config-server"
      - "http"
      - "-p"
      - ":8080"
      - "--auto-refresh-duration"
      - "10"


  consul:
    image: docker.io/bitnami/consul:1
    volumes:
      - ./consul_volume/:/bitnami/consul
    ports:
      - '8300:8300'
      - '8301:8301'
      - '8301:8301/udp'
      - '8500:8500'
      - '8600:8600'
